services:
  db:
    image: postgres:17
    container_name: colorful-nails-db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: colorful_nails
    ports:
      - "5432:5432"
    # Uncomment to keep data after container goes down
    # volumes: postgres_data:/var/lib/postgresql/data
